name: Render Notebooks to HTML branch

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  render-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Jupyter
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert

    - name: Convert Notebooks to HTML
      run: |
        mkdir -p rendered
        find . -name "*.ipynb" -exec jupyter nbconvert --to html --output-dir=rendered {} +

    - name: Push HTML to rendered-notebook branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DATE: $(date -u +'%Y-%m-%dT%H:%M:%SZ')  # 獲取當前 UTC 日期時間
        RUN_NUMBER: ${{ github.run_number }}  # 獲取 GitHub Actions 的運行次數
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout --orphan rendered-notebook
        git reset --hard
        git commit --allow-empty -m "[$DATE] GitHub Action Run #$RUN_NUMBER: Generate-Notebook-into-HTML"
        git checkout master
        cp -r rendered/* .
        git add .
        git commit -m "Add rendered HTML files"
        git push -f origin rendered-notebook